require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'FoodOrder' do
  permissions_path = '../node_modules/react-native-permissions/ios'
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'

  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'

  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'react-native-geolocation-service', :path => '../node_modules/react-native-geolocation-service'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-google-places', :path => '../node_modules/react-native-google-places'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'react-native-simple-toast', :path => '../node_modules/react-native-simple-toast'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'

  pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

  pod 'RNSha256', :path => '../node_modules/react-native-sha256'

  pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNAppleAuthentication', :path => '../node_modules/@invertase/react-native-apple-authentication'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'

  pod 'react-native-pager-view', :path => '../node_modules/react-native-pager-view'

  target 'FoodOrderTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
        config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        new_xcconfig = xcconfig.sub('HEADER_SEARCH_PATHS = $(inherited)', 'HEADER_SEARCH_PATHS = $(inherited) "$(PODS_TARGET_SRCROOT)/ReactCommon/jsiexecutor"')
        File.open(xcconfig_path, "w") { |file| file << new_xcconfig }
      end
    end
  end
end

# target 'OneSignalNotificationServiceExtension' do
#   pod 'OneSignal', '>= 3.0', '< 4.0'
# end